version: '3.8'

services:
  web:
    build: .
    command: uvicorn src.main:app --reload --workers 1 --host 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data